name: chembl-pipeline-deployment
flow_name: chembl_pipeline
entrypoint: app.orchestration.data_transformation:chembl_pipeline
work_pool:
  name: default
  job_variables: {}
tags: []
parameters: {}
schedule:
  type: cron
  cron: "0 0 * * *"   # run daily at midnight UTC
  timezone: "UTC"
description: "Deployment for chembl_pipeline"
image: ""